"""
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random
position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
"""


class Solution:
    # the slow dictionary approach
    def findTheDifference(self, s: str, t: str) -> str:
        tDict = {}
        for char in t:
            tDict[char] = tDict.get(char, 0) + 1

        for char in s:
            tDict[char] -= 1

        for k, v in tDict.items():
            if v == 1:
                return k

    # direct string operation
    def findTheDifference(self, s: str, t: str) -> str:
        for char in s:
            t = t.replace(char, '', 1)

        return t

    # the slow list operation
    def findTheDifference(self, s: str, t: str) -> str:
        s = list(s)
        t = list(t)
        for char in s:
            t.remove(char)
        return t[0]

    # the set and count approach, this should be the fastest one
    def findTheDifference(self, s: str, t: str) -> str:
        for char in set(t):
            if s.count(char) != t.count(char):
                return char